import {
  BadgeCheck,
  BarChart3,
  BriefcaseBusiness,
  Building2,
  CircleUserRound,
  FileText,
  Handshake,
  HelpCircle,
  MessageSquareText,
  Network,
  Rocket,
  Search,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Trophy,
  Users,
  WalletCards,
} from "lucide-react";

import type { EcosystemPageData } from "@/components/nearu/ecosystem-page";

export const ecosystemPages: Record<string, EcosystemPageData & { metaDescription: string }> = {
  "business-card": {
    eyebrow: "BNC for business",
    title: "Digital business cards for local shops",
    description:
      "Create a clean public identity for your shop with contact details, location, services, photos, and quick sharing.",
    primaryCta: "Create your card",
    primaryHref: "/admin",
    secondaryCta: "View marketplace",
    secondaryHref: "/",
    heroImage: "/mockup/im-card_banner.jpg",
    metaDescription: "Create and manage a digital business card for your local shop on Nearu.",
    stats: [
      { value: "5 min", label: "setup time" },
      { value: "24/7", label: "public profile" },
      { value: "1 link", label: "easy sharing" },
    ],
    features: [
      { title: "Public profile", text: "Show your business name, category, description, contact, and address in one place.", icon: CircleUserRound },
      { title: "Quick actions", text: "Help customers call, open directions, or share your listing faster.", icon: BadgeCheck },
      { title: "Photos and logo", text: "Use a clear logo or storefront image to make your listing recognizable.", icon: Sparkles },
      { title: "Admin updates", text: "Keep your business details fresh from the admin panel.", icon: Store },
    ],
    steps: [
      { title: "Add business details", text: "Enter name, category, location, contact, and description." },
      { title: "Publish your profile", text: "Make the listing visible in search and category pages." },
      { title: "Share with customers", text: "Use your listing link in chats, posters, and social profiles." },
    ],
  },
  b2b: {
    eyebrow: "Local network",
    title: "B2B discovery for nearby businesses",
    description:
      "Help shops, suppliers, and service providers find each other through verified local listings and category-based discovery.",
    primaryCta: "Explore businesses",
    primaryHref: "/",
    secondaryCta: "Add your business",
    secondaryHref: "/admin",
    heroImage: "/mockup/im-b2b_grocery.jpg",
    metaDescription: "Discover local B2B suppliers, services, and business partners through Nearu.",
    stats: [
      { value: "Local", label: "supplier search" },
      { value: "Fast", label: "contact flow" },
      { value: "Trusted", label: "profiles" },
    ],
    features: [
      { title: "Supplier discovery", text: "Find shops and service providers by category, rating, and location.", icon: Network },
      { title: "Business contacts", text: "Use phone and email fields to connect with the right person.", icon: Handshake },
      { title: "Category signals", text: "Featured and popular flags help highlight strong local providers.", icon: Star },
      { title: "Simple expansion", text: "The current data model can grow into quotes, RFQs, and supplier dashboards.", icon: Building2 },
    ],
    steps: [
      { title: "Search a category", text: "Browse suppliers and services relevant to your business." },
      { title: "Compare listings", text: "Review descriptions, contact details, ratings, and distance." },
      { title: "Start a conversation", text: "Call, email, or visit the provider directly." },
    ],
  },
  jobs: {
    eyebrow: "Local hiring",
    title: "Jobs for shops, services, and local talent",
    description:
      "A practical job board direction for local businesses to post roles and for nearby workers to discover opportunities.",
    primaryCta: "Browse businesses",
    primaryHref: "/",
    secondaryCta: "Post from admin",
    secondaryHref: "/admin",
    heroImage: "/mockup/im-occ_sales.jpg",
    metaDescription: "Local job discovery for shops, services, and small businesses on Nearu.",
    stats: [
      { value: "Local", label: "job matches" },
      { value: "Simple", label: "posting flow" },
      { value: "Mobile", label: "candidate ready" },
    ],
    features: [
      { title: "Role listings", text: "Prepare pages for sales, delivery, support, tailoring, beauty, and service roles.", icon: BriefcaseBusiness },
      { title: "Business context", text: "Connect jobs to existing business profiles so candidates know who is hiring.", icon: Store },
      { title: "Applicant actions", text: "Add call, WhatsApp, or apply links when the hiring backend is ready.", icon: MessageSquareText },
      { title: "Local filters", text: "Future filters can include area, role type, pay range, and experience.", icon: Search },
    ],
    steps: [
      { title: "Create a job post", text: "A business adds role, pay range, location, and contact details." },
      { title: "Candidates discover it", text: "Jobs appear by category and area once the module is connected." },
      { title: "Connect directly", text: "Candidates contact the business through the provided channel." },
    ],
  },
  "doctor-booking": {
    eyebrow: "Health appointments",
    title: "Doctor booking for nearby clinics",
    description:
      "A healthcare booking direction for BNC users to discover doctors, compare clinic availability, and request appointments from the local ecosystem.",
    primaryCta: "Find doctors",
    primaryHref: "/",
    secondaryCta: "Manage clinics",
    secondaryHref: "/admin",
    heroImage: "/mockup/im-pharmacy.jpg",
    metaDescription: "Book doctor appointments and discover nearby clinics through the BNC ecosystem.",
    stats: [
      { value: "Local", label: "clinic search" },
      { value: "Quick", label: "booking flow" },
      { value: "Trusted", label: "health profiles" },
    ],
    features: [
      { title: "Doctor discovery", text: "Prepare listings for doctors, clinics, departments, timings, and consultation details.", icon: Stethoscope },
      { title: "Appointment requests", text: "Connect call, WhatsApp, or booking actions when the scheduling backend is ready.", icon: MessageSquareText },
      { title: "Clinic profiles", text: "Use location, contact, ratings, and service details to help patients choose confidently.", icon: Store },
      { title: "Local health search", text: "Future filters can include specialty, area, availability, language, and visit type.", icon: Search },
    ],
    steps: [
      { title: "Choose a doctor", text: "Search by specialty, clinic, area, or healthcare need." },
      { title: "Check appointment options", text: "Review contact details, timings, and preferred booking channel." },
      { title: "Confirm visit", text: "Call, message, or submit a booking request through the connected clinic flow." },
    ],
  },
  winner: {
    eyebrow: "Rewards",
    title: "Campaigns, contests, and local winners",
    description:
      "A rewards page for marketplace campaigns, prize draws, seasonal offers, and winner announcements.",
    primaryCta: "See offers",
    primaryHref: "/",
    secondaryCta: "Manage campaigns",
    secondaryHref: "/admin",
    heroImage: "/mockup/im-gifts.jpg",
    metaDescription: "Explore Nearu campaigns, local contests, and winner announcements.",
    stats: [
      { value: "Seasonal", label: "campaigns" },
      { value: "Public", label: "winner posts" },
      { value: "Local", label: "shop offers" },
    ],
    features: [
      { title: "Winner board", text: "Show contest winners and campaign highlights in a public page.", icon: Trophy },
      { title: "Offer campaigns", text: "Connect deals and featured shops to promotions.", icon: Sparkles },
      { title: "Trust signals", text: "Use clear rules and winner history to make campaigns credible.", icon: ShieldCheck },
      { title: "Business participation", text: "Let shops sponsor campaigns or add prize offers later.", icon: Store },
    ],
    steps: [
      { title: "Launch a campaign", text: "Define title, dates, participating businesses, and reward details." },
      { title: "Collect entries", text: "Connect entry forms or offer actions when backend support is added." },
      { title: "Publish winners", text: "Display winners and related businesses on the page." },
    ],
  },
  feed: {
    eyebrow: "Community",
    title: "Local updates from shops and customers",
    description:
      "A feed direction for announcements, offers, new arrivals, event posts, and useful local updates.",
    primaryCta: "Discover shops",
    primaryHref: "/",
    secondaryCta: "Create update",
    secondaryHref: "/admin",
    heroImage: "/mockup/im-restaurant.jpg",
    metaDescription: "Read local business updates, offers, and community posts on Nearu.",
    stats: [
      { value: "Fresh", label: "updates" },
      { value: "Useful", label: "local posts" },
      { value: "Linked", label: "to listings" },
    ],
    features: [
      { title: "Business posts", text: "Prepare space for shops to share offers, new arrivals, and announcements.", icon: FileText },
      { title: "Listing links", text: "Each post can connect back to a business detail page.", icon: Store },
      { title: "Community signals", text: "Future reactions and shares can help rank useful updates.", icon: Users },
      { title: "Searchable updates", text: "Posts can later join catalog search and category pages.", icon: Search },
    ],
    steps: [
      { title: "Business creates update", text: "A shop posts an offer, announcement, or event." },
      { title: "Feed publishes it", text: "Customers see fresh posts from local businesses." },
      { title: "Customer takes action", text: "They open the business profile, call, or visit." },
    ],
  },
  plans: {
    eyebrow: "Pricing",
    title: "Simple plans for local business growth",
    description:
      "A clean plan page for free listings, featured placement, verified profiles, and business tools.",
    primaryCta: "Start free",
    primaryHref: "/admin",
    secondaryCta: "Compare listings",
    secondaryHref: "/",
    heroImage: "/mockup/im-supermarket.jpg",
    metaDescription: "Compare simple Nearu plans for local business listings and promotion.",
    stats: [
      { value: "Free", label: "basic listing" },
      { value: "Featured", label: "growth option" },
      { value: "Admin", label: "easy edits" },
    ],
    features: [
      { title: "Free listing", text: "Let businesses appear in catalog, category pages, and search.", icon: WalletCards },
      { title: "Featured placement", text: "Highlight selected businesses on homepage and category sections.", icon: Star },
      { title: "Verified profile", text: "Add stronger trust indicators and contact completeness.", icon: BadgeCheck },
      { title: "Performance view", text: "Connect dashboard metrics when tracking is available.", icon: BarChart3 },
    ],
    steps: [
      { title: "Choose a plan", text: "Start with a free listing or select a featured placement." },
      { title: "Complete profile", text: "Add contact, images, location, category, and description." },
      { title: "Grow visibility", text: "Use featured and popular signals to improve discovery." },
    ],
  },
  dashboard: {
    eyebrow: "Business tools",
    title: "A dashboard for managing your local listing",
    description:
      "The dashboard page gives business owners a direction for managing listings, performance, leads, and profile quality.",
    primaryCta: "Open admin",
    primaryHref: "/admin",
    secondaryCta: "View live catalog",
    secondaryHref: "/",
    heroImage: "/mockup/im-mobile.jpg",
    metaDescription: "Manage business listings, visibility, and profile quality with the Nearu dashboard direction.",
    stats: [
      { value: "Listings", label: "managed" },
      { value: "Leads", label: "future metric" },
      { value: "Quality", label: "profile score" },
    ],
    features: [
      { title: "Listing control", text: "Create and update business details from one place.", icon: Store },
      { title: "Visibility flags", text: "Set featured and popular flags for marketplace promotion.", icon: Star },
      { title: "Profile health", text: "Track missing image, address, contact, or category fields later.", icon: ShieldCheck },
      { title: "Performance metrics", text: "Prepare for views, calls, direction clicks, and search appearances.", icon: BarChart3 },
    ],
    steps: [
      { title: "Sign in", text: "Use the lightweight admin login configured for this project." },
      { title: "Manage listings", text: "Create, edit, feature, or delete business records." },
      { title: "Review performance", text: "Add metrics when analytics events are connected." },
    ],
  },
  help: {
    eyebrow: "Support",
    title: "Help for customers and business owners",
    description:
      "A support page for common marketplace questions, listing guidance, admin help, and contact paths.",
    primaryCta: "Browse catalog",
    primaryHref: "/",
    secondaryCta: "Go to admin",
    secondaryHref: "/admin",
    heroImage: "/mockup/im-grocery.jpg",
    metaDescription: "Get help using Nearu marketplace search, listings, categories, and admin tools.",
    stats: [
      { value: "Search", label: "catalog help" },
      { value: "Listings", label: "business help" },
      { value: "Admin", label: "setup help" },
    ],
    features: [
      { title: "Find a business", text: "Learn how search, categories, featured, and popular filters work.", icon: Search },
      { title: "Manage a listing", text: "Understand required business fields, category links, and images.", icon: Store },
      { title: "Troubleshooting", text: "Use clear error states and admin validation to recover from mistakes.", icon: HelpCircle },
      { title: "Next steps", text: "Prepare support docs for mobile app setup and production deployment.", icon: Rocket },
    ],
    steps: [
      { title: "Choose your topic", text: "Start with catalog browsing, business listing, or admin access." },
      { title: "Follow the guidance", text: "Use the page instructions and validation messages." },
      { title: "Contact support", text: "Add contact channels when the project has real support ownership." },
    ],
  },
};
