import 'catalog_models.dart';

const profileImageUrl =
    'https://images.pexels.com/photos/31721843/pexels-photo-31721843.jpeg?auto=compress&cs=tinysrgb&w=600';

final fallbackCatalog = CatalogData(
  categories: const [
    CategoryItem(
      id: '1',
      name: 'Grocery',
      slug: 'grocery',
      icon: 'shopping-cart',
      accent: '#FF5A4C',
      isActive: false,
    ),
    CategoryItem(
      id: '2',
      name: 'Restaurants',
      slug: 'restaurants',
      icon: 'utensils-crossed',
      accent: '#FFB01E',
      isActive: false,
    ),
    CategoryItem(
      id: '3',
      name: 'Tailors',
      slug: 'tailors',
      icon: 'scissors',
      accent: '#0B285E',
      isActive: true,
    ),
    CategoryItem(
      id: '4',
      name: 'Beauty',
      slug: 'beauty',
      icon: 'sparkles',
      accent: '#FF7186',
      isActive: false,
    ),
    CategoryItem(
      id: '5',
      name: 'Electronics',
      slug: 'electronics',
      icon: 'monitor-smartphone',
      accent: '#6A66FF',
      isActive: false,
    ),
    CategoryItem(
      id: '6',
      name: 'Home Services',
      slug: 'home-services',
      icon: 'house-plus',
      accent: '#4AB64B',
      isActive: false,
    ),
    CategoryItem(
      id: '7',
      name: 'More',
      slug: 'more',
      icon: 'layout-grid',
      accent: '#7183A6',
      isActive: false,
    ),
  ],
  featured: const [
    BusinessItem(
      id: '1',
      name: 'Spice Garden',
      subtitle: 'Restaurant',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.6,
      reviewCount: 126,
      distanceKm: 1.2,
      coverVariant: 'plate',
      imageUrl:
          'https://images.pexels.com/photos/20418288/pexels-photo-20418288.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Restaurants',
      isFeatured: true,
      isPopular: true,
      badgeText: '20% OFF',
      badgeColor: '#2961F0',
    ),
    BusinessItem(
      id: '2',
      name: 'Royale Tailors',
      subtitle: 'Tailor',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.7,
      reviewCount: 89,
      distanceKm: 1.5,
      coverVariant: 'suit',
      imageUrl:
          'https://images.pexels.com/photos/6766299/pexels-photo-6766299.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Tailors',
      isFeatured: true,
      isPopular: false,
      badgeText: 'Popular',
      badgeColor: '#FFAC1D',
    ),
    BusinessItem(
      id: '3',
      name: 'Fresh Basket',
      subtitle: 'Grocery',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.5,
      reviewCount: 162,
      distanceKm: 2.1,
      coverVariant: 'basket',
      imageUrl:
          'https://images.pexels.com/photos/9070106/pexels-photo-9070106.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Grocery',
      isFeatured: true,
      isPopular: true,
      badgeText: '10% OFF',
      badgeColor: '#35B44A',
    ),
    BusinessItem(
      id: '4',
      name: 'Hair Lounge',
      subtitle: 'Beauty Salon',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.6,
      reviewCount: 98,
      distanceKm: 2.4,
      coverVariant: 'salon',
      imageUrl:
          'https://images.pexels.com/photos/13068359/pexels-photo-13068359.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Beauty',
      isFeatured: true,
      isPopular: false,
    ),
  ],
  popular: const [
    BusinessItem(
      id: '1',
      name: 'Spice Garden',
      subtitle: 'Restaurant',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.6,
      reviewCount: 126,
      distanceKm: 1.2,
      coverVariant: 'plate',
      imageUrl:
          'https://images.pexels.com/photos/20418288/pexels-photo-20418288.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Restaurants',
      isFeatured: true,
      isPopular: true,
      badgeText: '20% OFF',
      badgeColor: '#2961F0',
    ),
    BusinessItem(
      id: '3',
      name: 'Fresh Basket',
      subtitle: 'Grocery',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.5,
      reviewCount: 162,
      distanceKm: 2.1,
      coverVariant: 'basket',
      imageUrl:
          'https://images.pexels.com/photos/9070106/pexels-photo-9070106.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Grocery',
      isFeatured: true,
      isPopular: true,
      badgeText: '10% OFF',
      badgeColor: '#35B44A',
    ),
    BusinessItem(
      id: '5',
      name: 'Quick Mart',
      subtitle: 'Grocery Store',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.6,
      reviewCount: 98,
      distanceKm: 1.2,
      coverVariant: 'shelf',
      imageUrl:
          'https://images.pexels.com/photos/16211537/pexels-photo-16211537.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Grocery',
      isFeatured: false,
      isPopular: true,
    ),
    BusinessItem(
      id: '6',
      name: 'Maya Beauty Salon',
      subtitle: 'Beauty Salon',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.7,
      reviewCount: 76,
      distanceKm: 1.3,
      coverVariant: 'salon',
      imageUrl:
          'https://images.pexels.com/photos/13068359/pexels-photo-13068359.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Beauty',
      isFeatured: false,
      isPopular: true,
    ),
    BusinessItem(
      id: '7',
      name: 'Tech Hub',
      subtitle: 'Electronics Store',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.5,
      reviewCount: 124,
      distanceKm: 1.6,
      coverVariant: 'phone',
      imageUrl:
          'https://images.pexels.com/photos/2818118/pexels-photo-2818118.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Electronics',
      isFeatured: false,
      isPopular: true,
    ),
    BusinessItem(
      id: '8',
      name: 'HomeFix Pro',
      subtitle: 'Home Services',
      area: 'Calicut',
      city: 'Kozhikode',
      rating: 4.6,
      reviewCount: 53,
      distanceKm: 2.4,
      coverVariant: 'worker',
      imageUrl:
          'https://images.pexels.com/photos/4981802/pexels-photo-4981802.jpeg?auto=compress&cs=tinysrgb&w=1200',
      categoryName: 'Home Services',
      isFeatured: false,
      isPopular: true,
    ),
  ],
  stats: const CatalogStats(
    categories: 7,
    businesses: 10,
    trusted: 6,
    happyUsers: '10K+',
  ),
);
