import 'catalog_models.dart';

const profileImageUrl =
    'https://images.pexels.com/photos/31721843/pexels-photo-31721843.jpeg?auto=compress&cs=tinysrgb&w=600';

const _imageByVariant = {
  'plate':
      'https://images.pexels.com/photos/20418288/pexels-photo-20418288.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'suit':
      'https://images.pexels.com/photos/6766299/pexels-photo-6766299.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'basket':
      'https://images.pexels.com/photos/9070106/pexels-photo-9070106.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'salon':
      'https://images.pexels.com/photos/13068359/pexels-photo-13068359.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'shelf':
      'https://images.pexels.com/photos/16211537/pexels-photo-16211537.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'phone':
      'https://images.pexels.com/photos/2818118/pexels-photo-2818118.jpeg?auto=compress&cs=tinysrgb&w=1200',
  'worker':
      'https://images.pexels.com/photos/4981802/pexels-photo-4981802.jpeg?auto=compress&cs=tinysrgb&w=1200',
};

const _fallbackCategories = [
  CategoryItem(
    id: '1',
    name: 'Grocery',
    slug: 'grocery',
    icon: 'shopping-cart',
    accentColor: '#FF5A4C',
    isActive: true,
    sortOrder: 1,
  ),
  CategoryItem(
    id: '2',
    name: 'Restaurants',
    slug: 'restaurants',
    icon: 'utensils-crossed',
    accentColor: '#FFB01E',
    isActive: true,
    sortOrder: 2,
  ),
  CategoryItem(
    id: '3',
    name: 'Bakery & Sweets',
    slug: 'bakery-sweets',
    icon: 'utensils-crossed',
    accentColor: '#D94842',
    isActive: false,
    sortOrder: 3,
  ),
  CategoryItem(
    id: '4',
    name: 'Tailors',
    slug: 'tailors',
    icon: 'scissors',
    accentColor: '#0B285E',
    isActive: true,
    sortOrder: 4,
  ),
  CategoryItem(
    id: '5',
    name: 'Beauty',
    slug: 'beauty',
    icon: 'sparkles',
    accentColor: '#FF7186',
    isActive: true,
    sortOrder: 5,
  ),
  CategoryItem(
    id: '6',
    name: 'Electronics',
    slug: 'electronics',
    icon: 'monitor-smartphone',
    accentColor: '#6A66FF',
    isActive: true,
    sortOrder: 6,
  ),
  CategoryItem(
    id: '7',
    name: 'Home Services',
    slug: 'home-services',
    icon: 'house-plus',
    accentColor: '#4AB64B',
    isActive: true,
    sortOrder: 7,
  ),
  CategoryItem(
    id: '8',
    name: 'Pharmacy',
    slug: 'pharmacy',
    icon: 'layout-grid',
    accentColor: '#1F9D7A',
    isActive: false,
    sortOrder: 8,
  ),
  CategoryItem(
    id: '9',
    name: 'Gifts & Stationery',
    slug: 'gifts-stationery',
    icon: 'layout-grid',
    accentColor: '#8A5BFF',
    isActive: false,
    sortOrder: 9,
  ),
  CategoryItem(
    id: '10',
    name: 'More',
    slug: 'more',
    icon: 'layout-grid',
    accentColor: '#7183A6',
    isActive: false,
    sortOrder: 10,
  ),
];

final _businesses = [
  BusinessItem(
    id: '1',
    slug: 'spice-garden',
    name: 'Spice Garden',
    subtitle: 'Family Restaurant',
    area: 'Mavoor Road',
    city: 'Kozhikode',
    rating: 4.6,
    reviewCount: 126,
    distanceKm: 1.2,
    coverVariant: 'plate',
    imageUrl: _imageByVariant['plate']!,
    categoryId: '2',
    categoryName: 'Restaurants',
    categorySlug: 'restaurants',
    isFeatured: true,
    isPopular: true,
    badgeText: '20% OFF',
    badgeColor: '#2961F0',
    tags: ['restaurants', 'Family Restaurant', 'Mavoor Road', 'featured', 'popular'],
  ),
  BusinessItem(
    id: '2',
    slug: 'paragon-bites',
    name: 'Paragon Bites',
    subtitle: 'Malabar Restaurant',
    area: 'Kannur Road',
    city: 'Kozhikode',
    rating: 4.8,
    reviewCount: 214,
    distanceKm: 1.9,
    coverVariant: 'plate',
    imageUrl: _imageByVariant['plate']!,
    categoryId: '2',
    categoryName: 'Restaurants',
    categorySlug: 'restaurants',
    isFeatured: true,
    isPopular: true,
    badgeText: 'Top Rated',
    badgeColor: '#D94842',
    tags: ['restaurants', 'Malabar Restaurant', 'Kannur Road', 'featured', 'popular'],
  ),
  BusinessItem(
    id: '3',
    slug: 'fresh-basket',
    name: 'Fresh Basket',
    subtitle: 'Fruit & Vegetable Store',
    area: 'Palayam',
    city: 'Kozhikode',
    rating: 4.5,
    reviewCount: 162,
    distanceKm: 2.1,
    coverVariant: 'basket',
    imageUrl: _imageByVariant['basket']!,
    categoryId: '1',
    categoryName: 'Grocery',
    categorySlug: 'grocery',
    isFeatured: true,
    isPopular: true,
    badgeText: '10% OFF',
    badgeColor: '#35B44A',
    tags: ['grocery', 'Fruit & Vegetable Store', 'Palayam', 'featured', 'popular'],
  ),
  BusinessItem(
    id: '4',
    slug: 'sweet-crumbs-bakery',
    name: 'Sweet Crumbs Bakery',
    subtitle: 'Bakery & Cakes',
    area: 'Nadakkavu',
    city: 'Kozhikode',
    rating: 4.7,
    reviewCount: 144,
    distanceKm: 2.5,
    coverVariant: 'basket',
    imageUrl: _imageByVariant['basket']!,
    categoryId: '3',
    categoryName: 'Bakery & Sweets',
    categorySlug: 'bakery-sweets',
    isFeatured: true,
    isPopular: true,
    badgeText: 'Fresh Today',
    badgeColor: '#D94842',
    tags: ['bakery-sweets', 'Bakery & Cakes', 'Nadakkavu', 'featured', 'popular'],
  ),
  BusinessItem(
    id: '5',
    slug: 'royale-tailors',
    name: 'Royale Tailors',
    subtitle: 'Men\'s Tailor',
    area: 'SM Street',
    city: 'Kozhikode',
    rating: 4.7,
    reviewCount: 89,
    distanceKm: 1.5,
    coverVariant: 'suit',
    imageUrl: _imageByVariant['suit']!,
    categoryId: '4',
    categoryName: 'Tailors',
    categorySlug: 'tailors',
    isFeatured: true,
    isPopular: true,
    badgeText: 'Popular',
    badgeColor: '#FFAC1D',
    tags: ['tailors', 'Men\'s Tailor', 'SM Street', 'featured', 'popular'],
  ),
  BusinessItem(
    id: '6',
    slug: 'glow-bridal-studio',
    name: 'Glow Bridal Studio',
    subtitle: 'Bridal Makeup',
    area: 'Thondayad',
    city: 'Kozhikode',
    rating: 4.8,
    reviewCount: 54,
    distanceKm: 4.1,
    coverVariant: 'salon',
    imageUrl: _imageByVariant['salon']!,
    categoryId: '5',
    categoryName: 'Beauty',
    categorySlug: 'beauty',
    isFeatured: true,
    isPopular: false,
    badgeText: 'Bridal',
    badgeColor: '#B83280',
    tags: ['beauty', 'Bridal Makeup', 'Thondayad', 'featured'],
  ),
  BusinessItem(
    id: '7',
    slug: 'digital-point',
    name: 'Digital Point',
    subtitle: 'Laptop & Mobile Service',
    area: 'Palazhi',
    city: 'Kozhikode',
    rating: 4.4,
    reviewCount: 73,
    distanceKm: 3.1,
    coverVariant: 'phone',
    imageUrl: _imageByVariant['phone']!,
    categoryId: '6',
    categoryName: 'Electronics',
    categorySlug: 'electronics',
    isFeatured: true,
    isPopular: false,
    badgeText: 'Service',
    badgeColor: '#6A66FF',
    tags: ['electronics', 'Laptop & Mobile Service', 'Palazhi', 'featured'],
  ),
  BusinessItem(
    id: '8',
    slug: 'spark-electricals',
    name: 'Spark Electricals',
    subtitle: 'Electrician Services',
    area: 'Medical College',
    city: 'Kozhikode',
    rating: 4.5,
    reviewCount: 61,
    distanceKm: 3.8,
    coverVariant: 'worker',
    imageUrl: _imageByVariant['worker']!,
    categoryId: '7',
    categoryName: 'Home Services',
    categorySlug: 'home-services',
    isFeatured: true,
    isPopular: false,
    badgeText: 'Same Day',
    badgeColor: '#4AB64B',
    tags: ['home-services', 'Electrician Services', 'Medical College', 'featured'],
  ),
  BusinessItem(
    id: '9',
    slug: 'quick-mart',
    name: 'Quick Mart',
    subtitle: 'Neighbourhood Grocery',
    area: 'Eranhipalam',
    city: 'Kozhikode',
    rating: 4.3,
    reviewCount: 98,
    distanceKm: 1.2,
    coverVariant: 'shelf',
    imageUrl: _imageByVariant['shelf']!,
    categoryId: '1',
    categoryName: 'Grocery',
    categorySlug: 'grocery',
    isFeatured: false,
    isPopular: true,
    tags: ['grocery', 'Neighbourhood Grocery', 'Eranhipalam', 'popular'],
  ),
  BusinessItem(
    id: '10',
    slug: 'maya-beauty-salon',
    name: 'Maya Beauty Salon',
    subtitle: 'Beauty Salon',
    area: 'Kakkanchery',
    city: 'Kozhikode',
    rating: 4.7,
    reviewCount: 76,
    distanceKm: 1.3,
    coverVariant: 'salon',
    imageUrl: _imageByVariant['salon']!,
    categoryId: '5',
    categoryName: 'Beauty',
    categorySlug: 'beauty',
    isFeatured: false,
    isPopular: true,
    badgeText: 'New Offers',
    badgeColor: '#FF7186',
    tags: ['beauty', 'Beauty Salon', 'Kakkanchery', 'popular'],
  ),
  BusinessItem(
    id: '11',
    slug: 'tech-hub',
    name: 'Tech Hub',
    subtitle: 'Mobile & Accessories',
    area: 'Mavoor Road',
    city: 'Kozhikode',
    rating: 4.5,
    reviewCount: 124,
    distanceKm: 1.6,
    coverVariant: 'phone',
    imageUrl: _imageByVariant['phone']!,
    categoryId: '6',
    categoryName: 'Electronics',
    categorySlug: 'electronics',
    isFeatured: false,
    isPopular: true,
    tags: ['electronics', 'Mobile & Accessories', 'Mavoor Road', 'popular'],
  ),
  BusinessItem(
    id: '12',
    slug: 'homefix-pro',
    name: 'HomeFix Pro',
    subtitle: 'Plumbing & Repairs',
    area: 'Chevayur',
    city: 'Kozhikode',
    rating: 4.6,
    reviewCount: 53,
    distanceKm: 2.4,
    coverVariant: 'worker',
    imageUrl: _imageByVariant['worker']!,
    categoryId: '7',
    categoryName: 'Home Services',
    categorySlug: 'home-services',
    isFeatured: false,
    isPopular: true,
    tags: ['home-services', 'Plumbing & Repairs', 'Chevayur', 'popular'],
  ),
  BusinessItem(
    id: '13',
    slug: 'careplus-pharmacy',
    name: 'CarePlus Pharmacy',
    subtitle: 'Pharmacy',
    area: 'Nadakkavu',
    city: 'Kozhikode',
    rating: 4.3,
    reviewCount: 82,
    distanceKm: 1.7,
    coverVariant: 'shelf',
    imageUrl: _imageByVariant['shelf']!,
    categoryId: '8',
    categoryName: 'Pharmacy',
    categorySlug: 'pharmacy',
    isFeatured: false,
    isPopular: true,
    badgeText: '24/7',
    badgeColor: '#1F9D7A',
    tags: ['pharmacy', 'Nadakkavu', 'popular'],
  ),
  BusinessItem(
    id: '14',
    slug: 'paper-trail',
    name: 'Paper Trail',
    subtitle: 'Stationery & Gifts',
    area: 'Mananchira',
    city: 'Kozhikode',
    rating: 4.4,
    reviewCount: 46,
    distanceKm: 1.4,
    coverVariant: 'basket',
    imageUrl: _imageByVariant['basket']!,
    categoryId: '9',
    categoryName: 'Gifts & Stationery',
    categorySlug: 'gifts-stationery',
    isFeatured: false,
    isPopular: false,
    tags: ['gifts-stationery', 'Stationery & Gifts', 'Mananchira'],
  ),
];

final fallbackCatalog = CatalogData(
  categories: _fallbackCategories,
  featured: _businesses.where((business) => business.isFeatured).toList(),
  popular: _businesses.where((business) => business.isPopular).toList(),
  all: _businesses,
  stats: CatalogStats(
    categories: _fallbackCategories.length,
    businesses: _businesses.length,
    trusted: _businesses.where((business) => business.isPopular).length,
    happyUsers: '10K+',
  ),
);
