"use client";
import { Archive, Eye, LoaderCircle, Plus, ShieldAlert, Store } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { DashboardShell } from "@/components/dashboard-shell";
import type { BncSessionUser } from "@/lib/auth-types";
import { appPath, readJsonResponse } from "@/lib/client-routing";

type Listing = { id: string; name: string; slug: string; status: string; listingStatus: string; verified: boolean; shortDescription: string | null; logoUrl: string | null; locations: Array<{ locality: string; city: string }>; categories: Array<{ category: { name: string } }> };
export function MerchantListingsManager({ user }: { user: BncSessionUser }) {
  const [rows, setRows] = useState<Listing[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(appPath("/api/merchant/listings")); const body = await readJsonResponse<{ data?: Listing[]; message?: string | string[] }>(response, "Listings returned an unreadable response."); if (!response.ok || !body.data) throw new Error(Array.isArray(body.message) ? body.message.join(" ") : body.message ?? "Listings could not be loaded."); setRows(body.data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Listings could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  async function action(id: string, value: "PUBLISH" | "UNPUBLISH" | "ARCHIVE") { if (["UNPUBLISH", "ARCHIVE"].includes(value) && !window.confirm(value === "ARCHIVE" ? "Archive this listing? It will leave your active workspace." : "Unpublish this listing from public discovery?")) return; setError(""); setNotice(""); const response = await fetch(appPath(`/api/merchant/listings/${encodeURIComponent(id)}/action`), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: value }) }); const body = await response.json().catch(() => null) as { message?: string | string[] } | null; if (!response.ok) { setError(Array.isArray(body?.message) ? body.message.join(" ") : body?.message ?? "Listing status could not be changed."); return; } setNotice(`Listing ${value.toLowerCase()} completed.`); await load(); }
  return <DashboardShell mode="business" user={user}><section className="manager-heading"><div><span className="eyebrow">Merchant listings</span><h1>My listings</h1><p>Create, preview, edit, publish, unpublish, or archive only the listings available to your authenticated workspace.</p></div><Link className="admin-primary-link" href="/merchant/listings/new"><Plus size={16} /> Create listing</Link></section>{notice && <p className="settings-saved" role="status">{notice}</p>}{error && <p className="form-error" role="alert"><ShieldAlert size={16} /> {error}</p>}<section className="manager-table-card">{loading ? <div className="admin-empty"><LoaderCircle className="spin" size={30} /><strong>Loading listings</strong></div> : rows.length ? <div className="business-workspace-list">{rows.filter((row) => row.listingStatus !== "ARCHIVED").map((row) => <article key={row.id}><span><Store size={19} /></span><div><strong>{row.name}</strong><small>{row.listingStatus.replaceAll("_", " ")} · {row.status.replaceAll("_", " ")} · {row.locations[0]?.locality || row.locations[0]?.city || "No location"}</small></div><div className="admin-verification-actions"><Link href={`/merchant/listings/${row.id}/preview`}><Eye size={15} /> Preview</Link><Link href={`/merchant/listings/${row.id}/edit`}>Edit</Link>{row.listingStatus === "PUBLISHED" ? <button type="button" onClick={() => void action(row.id, "UNPUBLISH")}>Unpublish</button> : row.listingStatus !== "DISABLED" && <button type="button" onClick={() => void action(row.id, "PUBLISH")}>Publish</button>}<button type="button" onClick={() => void action(row.id, "ARCHIVE")}><Archive size={15} /> Archive</button></div></article>)}</div> : <div className="admin-empty"><Store size={30} /><strong>No listings yet</strong><span>Create your first business listing to begin.</span><Link href="/merchant/listings/new">Create listing</Link></div>}</section></DashboardShell>;
}
