"use client";
import { LoaderCircle, MapPin, ShieldAlert, Store } from "lucide-react";
import Image from "next/image";
import { useEffect, useState } from "react";
import { DashboardShell } from "@/components/dashboard-shell";
import type { BncSessionUser } from "@/lib/auth-types";
import { appPath, readJsonResponse } from "@/lib/client-routing";
type Listing = { name: string; description: string; shortDescription: string | null; logoUrl: string | null; coverImageUrl: string | null; publicPhone: string | null; email: string | null; websiteUrl: string | null; listingStatus: string; tags: string[]; seoTitle: string | null; seoDescription: string | null; locations: Array<{ addressLine1: string; locality: string; city: string; district: string; state: string; postalCode: string }>; categories: Array<{ category: { name: string } }>; media: Array<{ id: string; publicUrl: string; altText: string | null }> };
export function MerchantListingPreview({ user, id }: { user: BncSessionUser; id: string }) { const [data, setData] = useState<Listing | null>(null), [error, setError] = useState(""); useEffect(() => { void fetch(appPath(`/api/merchant/listings/${encodeURIComponent(id)}`)).then(async (response) => { const body = await readJsonResponse<{ data?: Listing; message?: string }>(response, "Preview returned an unreadable response."); if (!response.ok || !body.data) throw new Error(body.message ?? "Preview unavailable."); setData(body.data); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Preview unavailable.")); }, [id]); return <DashboardShell mode="business" user={user}>{error ? <div className="admin-empty"><ShieldAlert size={30} /><strong>{error}</strong></div> : !data ? <div className="admin-empty"><LoaderCircle className="spin" size={30} /><strong>Loading preview</strong></div> : <section className="profile-content-card"><span className="eyebrow">Private listing preview · {data.listingStatus}</span>{data.coverImageUrl && <Image src={data.coverImageUrl} alt="Listing cover" width={1000} height={360} unoptimized />}<header><Store size={24} />{data.logoUrl && <Image src={data.logoUrl} alt="Listing logo" width={80} height={80} unoptimized />}<div><h1>{data.name}</h1><p>{data.categories.map((item) => item.category.name).join(" · ")}</p></div></header><h2>{data.shortDescription}</h2><p>{data.description}</p>{data.locations[0] && <p><MapPin size={16} /> {[data.locations[0].addressLine1, data.locations[0].locality, data.locations[0].city, data.locations[0].district, data.locations[0].state, data.locations[0].postalCode].join(", ")}</p>}<p>{[data.publicPhone, data.email, data.websiteUrl].filter(Boolean).join(" · ")}</p><div>{data.tags?.map((tag) => <span className="admin-status" key={tag}>{tag}</span>)}</div>{data.media?.length > 0 && <div className="business-profile-gallery-manager">{data.media.map((media) => <Image key={media.id} src={media.publicUrl} alt={media.altText ?? data.name} width={180} height={120} unoptimized />)}</div>}</section>}</DashboardShell>; }
